---
title: "Basic processing"
output: html_document
vignette: >
  %\VignetteIndexEntry{Basic processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Process synchronously

Pass a single-page pdf or image file to Document AI and get the output immediately:

```{r, eval=FALSE}
library(daiR)
## Not run:
myfile <- "sample.pdf"
text <- get_text(dai_sync(myfile))
```

### Process asynchronously

Send larger batches for offline processing in three steps:

#### 1. Upload files to your Google Storage bucket

```{r, eval=FALSE}
## Not run:
library(googleCloudStorageR)
library(purrr)
my_pdfs <- c("sample1.pdf", "sample2.pdf")
map(my_pdfs, ~ gcs_upload(.x, name = basename(.x)))
```

#### 2. Tell Document AI to process them:

```{r, eval=FALSE}
## Not run:
dai_async(my_pdfs)
```

#### 3. Download the json output and extract the text:

```{r, eval=FALSE}
## Not run:
library(purrr)
bucket_contents <- gcs_list_objects()
jsons <- grep("*.json", bucket_contents$name, value = TRUE)
map(jsons, ~ gcs_get_object(.x, saveToDisk = basename(.x)))
local_jsons <- basename(jsons)
map(local_jsons, ~ get_text(.x, type = "async", save_to_file = TRUE))
```
